#!/bin/bash

#PBS -l nodes=1:ppn=2:gpus=1,walltime=24:00:00
#PBS -N yw2303_go_001
#PBS -M yw2303@nyu.edu
#PBS -m abe
#PBS -e localhost:$PBS_O_WORKDIR/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:$PBS_O_WORKDIR/${PBS_JOBNAME}.o${PBS_JOBID}
#PBS -l mem=8GB
module load torch/gnu
cd /home/yw2303/CV/darkforestGo
th train.lua --nGPU 1 --epoch_size 256 --epoch_size_test 256 --num_forward_models 2048 --data_augmentation &> darkgo_kgs_alpha_001

exit 0;
